# Generated by Django 2.2.16 on 2021-08-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20210820_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
